#!/usr/bin/env bash

if [-z "$1" ]; them
	echo "There needs to be a bucket name eg ./bucket my-bucket-name"
	exit 1
fi

BUCKET_NAME= $1

aws s3api create-bucket --bucket $BUCKET_NAME --create-bucket-configuration="LocationConstraint=<location>"